apiVersion: v1
appVersion: 1.7.1
description: CoreDNS is a DNS server that chains plugins and provides Kubernetes DNS
  Services
home: https://coredns.io
icon: https://coredns.io/images/CoreDNS_Colour_Horizontal.png
keywords:
- coredns
- dns
- kubedns
name: rke2-coredns
sources:
- https://github.com/coredns/coredns
version: 1.13.800
